### ISSUE TITLE
History: incorrect ScanTime dimension

### ISSUE THREAD

**Issue by moisseev** [vstakhov/rspamd-interface#13]
The table header is `Scan Time (ms)`, but scan time is displayed on the history page in seconds rounded up to seconds.
![2015-11-02 09_34_14-rspamd web interface - pale moon](https://cloud.githubusercontent.com/assets/2275981/10875562/0045a440-8145-11e5-810e-c1d185c64f42.png)

**Comment by vstakhov** [comment]
There are two bugs that caused this issue, I'm afraid.
